#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"
org.gradle.caching=true
org.gradle.configuration-cache=true

#Kotlin
kotlin.code.style=official

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true

githubPackagesUsername=kneeman
githubPackagesPassword=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